/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter8.h"
#include "LCD.h"
#include "PGA_1.h"
#include "PGA_2.h"
#include "PGA_3.h"
#include "TRIADC.h"
#include "UART.h"

#endif
